# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-25 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zpinfo',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
